#!/usr/bin/env python3
"""Regenerate ui_lambda/v2/options-data.js — the embedded dataset behind the
OPTIONS tab's per-stock simulation explorer and doc audit.

Reruns the judged window (2023 -> present, no-stop variant, earnings filter
ON — identical to the committed verdict) with the enriched trade log, plus
cycle-level counts of how many entry opportunities each doc rule removed.
"""
from __future__ import annotations

import datetime
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from options.backtest import (build_cycles, monthly_expiry_dates, run_backtest,  # noqa: E402
                              summary_stats, _archive_days)
from options.config import JUDGE_CAPITAL  # noqa: E402
from options.filters import in_blackout, in_earnings_window, load_blackouts  # noqa: E402
from options.underlying import AdjustedCloseStore  # noqa: E402

JUDGED_START, JUDGED_END = "2023-01-01", "2026-08-18"


def cycle_filter_counts(archive_root: pathlib.Path) -> dict:
    trading_days = _archive_days(archive_root, JUDGED_START, JUDGED_END)
    expiries = monthly_expiry_dates(archive_root, JUDGED_START, JUDGED_END)
    cycles = build_cycles(expiries, trading_days)
    blackout_ranges = load_blackouts(REPO_ROOT / "data" / "options_blackouts.yaml")
    blackout_hits, earnings_hits, clean = 0, 0, 0
    for cycle in cycles:
        entry = datetime.date.fromisoformat(cycle["entry_date"])
        expiry = datetime.date.fromisoformat(cycle["expiry"])
        if in_blackout(entry, expiry, blackout_ranges):
            blackout_hits += 1
        elif in_earnings_window(entry, expiry):
            earnings_hits += 1
        else:
            clean += 1
    return {"total_cycles": len(cycles), "blackout_cycles": blackout_hits,
            "earnings_cycles": earnings_hits, "tradeable_cycles": clean}


def main() -> int:
    archive_root = REPO_ROOT / "data" / "fo_bhavcopy"
    close_store = AdjustedCloseStore(REPO_ROOT / "data" / "qlib_data" / "in_data")
    result = run_backtest(archive_root, close_store, JUDGED_START, JUDGED_END,
                          stop_key="none", use_earnings_filter=True,
                          capital=JUDGE_CAPITAL,
                          blackouts_path=REPO_ROOT / "data" / "options_blackouts.yaml")
    stats = summary_stats(result)
    trades = result["trades"]

    trades_by_symbol: dict[str, list[dict]] = {}
    for trade in sorted(trades, key=lambda t: t["entry_date"]):
        rounded = {key: (round(value, 4) if isinstance(value, float) else value)
                   for key, value in trade.items()}
        trades_by_symbol.setdefault(trade["symbol"], []).append(rounded)

    exit_reasons = {"target": 0, "time": 0, "stop": 0}
    for trade in trades:
        exit_reasons[trade["exit_reason"]] += 1

    payload = {
        "generated_at": datetime.date.today().isoformat(),
        "window": {"start": JUDGED_START, "end": JUDGED_END},
        "stats": {key: (round(value, 4) if isinstance(value, float) else value)
                  for key, value in stats.items()},
        "exit_reasons": exit_reasons,
        "breached_trades": sum(1 for t in trades if t["breached"]),
        "cycle_filters": cycle_filter_counts(archive_root),
        "trades_by_symbol": trades_by_symbol,
    }
    out_path = REPO_ROOT / "ui_lambda" / "v2" / "options-data.js"
    out_path.write_text("/* Generated by examples/nse_options_export_ui_data.py"
                        " — do not hand-edit. */\n"
                        "window.OPTIONS_DATA = "
                        + json.dumps(payload, indent=1) + ";\n")
    print(f"wrote {out_path} · {len(trades)} trades · "
          f"{len(trades_by_symbol)} symbols · exits {exit_reasons} · "
          f"cycles {payload['cycle_filters']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
